utils:
  permission: 'skycloud.admin'
  noPerm: "&cI'm sorry, but you do not have permission to perform this command. Please contact the server administrators if you believe that this is in error."

spawnpoint:
  world: world
  x: 0
  y: 85
  z: 0
  yaw: 0
  pitch: 0

voidLimit: 50

blockedCommands:
  - 'pl'
  - 'plugins'
  - '?'
  - 'icanhasbukkit'

connectMessage:
  - ""
  - "   &c&lSkyCloud &e2.0"
  - "   &7Welcome back! Enjoy your stay."
  - ""
  - "   &7Click on your compass to navigate across our network!"
  - ""
  - "   &dDiscord: &fdiscord.skycloud.gg"
  - "   &bStore: &fstore.skycloud.gg"
  - ""