name: SkyHub
version: '${project.version}'
main: xyz.lotho.me.SkyHub
api-version: 1.8.8
authors: [ Lotho ]
description: An advanced hub plugin.

commands:
  spawn:
  setspawn:
  setvoidlimit:
  leavequeue:
    aliases: [lq]
  adminbypass:
    aliases: [ab]

depend:
  - PlaceholderAPI