name: SkyHub
version: '${project.version}'
main: xyz.lotho.me.SkyHub
api-version: 1.18
authors: [ Lotho ]
description: An advanced hub plugin.

commands:
  spawn:
  setspawn:
  setvoidlimit:
  adminbypass:
    aliases: [ab]
